In [2]:
## Pandas version 
import pandas as pd
pd.__version__

'3.0.5'

In [3]:
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
df = pd.read_csv('car_fuel_efficiency_2026.csv')
df.head()

--2026-09-22 00:13:59--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv.2’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.01s

2026-09-22 00:13:59 (47.3 MB/s) - ‘car_fuel_efficiency_2026.csv.2’ saved [635180/635180]

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [4]:
df.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [5]:
df.fuel_type.describe()

count        10000
unique           3
top       Gasoline
freq          6913
Name: fuel_type, dtype: object

In [6]:
df.fuel_efficiency_mpg.max()

np.float64(41.2)

In [ ]:
## 6. Median value of horsepower 
df_hp['horsepower'] = df['horsepower']
a = df_hp.horsepower.median()
print(a)
b = df_hp.horsepower.mode()[0]
print(b)
df.horsepower.isnull().sum()
df.horsepower.fillna(b)
c = df_hp.horsepower.mode()[0]
print(c)

254.0
252.0
252.0

In [83]:
## 7. Sum of weights 
# iloc = INTEGER location (select by position, like a list) Syntax for both:  df.iloc[ROWS, COLUMNS]
import numpy as np
df_asia = df.loc[df['origin'] =='Asia',['vehicle_weight', 'model_year']]
x = df_asia.head(7).to_numpy()
x_t = x.T
XTX = x_t @ x

XTX_inv = np.linalg.inv(XTX)
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

x_t.shape
#XTX.shape
#XTX_inv.shape

w = XTX_inv @ x_t @ y
w[:].sum()

np.float64(0.36919696904925486)

In [9]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64